### ISSUE TITLE
License

### ISSUE THREAD

**Issue by stephenpardy** [icc2115/sage#1]
Hi Ian.

I came across this package today from your very nice paper on the arXiv "Understanding Global Feature Contributions Through Additive Importance Measures." I am excited to try out this code, but I don't see a license. Would you be willing to clarify what the license is and add a `LICENSE.txt` file?

Thanks!

**Comment by icc2115** [comment]
Hi Stephen, thanks for pointing this out and sorry for the inconvenience. I just added the MIT license. I hope the code works out for you, let me know if you run into any issues!

Ian
